
services:
    iris:
        build: ./image-iris
        environment:
            IRIS_USERNAME: superuser
            IRIS_PASSWORD: SYS
        hostname: 2024demo
        container_name: mpidemo
        ports:
            - 1980:1972 
            - 52880:52773
        volumes:
            - D:\Coding\EMPIDemo\image-iris\llm\text2vec-base-chinese:/isc/model/text2vec
        command: 
            - -a
            - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
            - --check-caps false
            - --log /usr/irissys/mgr/messages.log
        

